username: elastic
password: eZr4ltvT
elastic_index: praza_qwen_all-minilm-l6-v2_chunked #contexts_qwen_eval
elastic_url: http://localhost:5601 # Not work with https, only with http
api_endpoint: http://localhost:9200